services:
  pdf-extractor:
    build: .
    container_name: pdf_vulnerability_extractor
    volumes:
      - ./:/pdf_reader_tenableWAS/host
      - ./output:/pdf_reader_tenableWAS/output
      - ./config.json:/pdf_reader_tenableWAS/config.json
    environment:
      - PYTHONPATH=/pdf_reader_tenableWAS
    command: ["--pdf", "/pdf_reader_tenableWAS/WAS_Web_app_scan_Juice_Shop___bWAAP-2[1].pdf", "--save-all"]